droppped_columns = [
    "season_x",
    "opp_team_name",
    "opponent_team",
    "result",
    "position",
    "assists",
    "penalties_missed",
    "bonus",
    "bps",
    "clean_sheets",
    "creativity",
    "element",
    "fixture",
    "goals_conceded",
    "goals_scored",
    "ict_index",
    "influence",
    "own_goals",
    "penalties_saved",
    "red_cards",
    "round",
    "saves",
    "selected",
    "team_a_score",
    "team_h_score",
    "threat",
    "transfers_balance",
    "transfers_in",
    "transfers_out",
    "value",
    "yellow_cards",
    "result_difference",
    "name_ex",
]


forward_statistics = [
    "result",
    "assists",
    "creativity",
    "goals_scored",
    "clean_sheets",
    "result",
    "value",
    "bps",
    "bonus",
    "goals_conceded",
    "saves",
    "ict_index",
    "influence",
    "penalties_saved",
    "team_h_score",
    "team_a_score",
    "threat",
    "result_difference",
    "yellow_cards",
    "was_home",
    "minutes",
    "total_points",
]


midfielder_statistics = [
    "assists",
    "opp_team_name",
    "result",
    "creativity",
    "goals_scored",
    "clean_sheets",
    "value",
    "bps",
    "bonus",
    "goals_conceded",
    "saves",
    "ict_index",
    "influence",
    "penalties_saved",
    "team_h_score",
    "team_a_score",
    "threat",
    "result_difference",
    "yellow_cards",
    "was_home",
    "minutes",
    "total_points",
]

goalkeeper_statistics = [
    "clean_sheets",
    "result",
    "value",
    "bps",
    "bonus",
    "goals_conceded",
    "saves",
    "ict_index",
    "influence",
    "penalties_saved",
    "team_h_score",
    "team_a_score",
    "threat",
    "result_difference",
    "yellow_cards",
    "was_home",
    "minutes",
    "total_points",
]
defender_statistics = [
    "assists",
    "creativity",
    "goals_scored",
    "clean_sheets",
    "result",
    "value",
    "bps",
    "bonus",
    "goals_conceded",
    "saves",
    "ict_index",
    "influence",
    "penalties_saved",
    "team_h_score",
    "team_a_score",
    "threat",
    "result_difference",
    "yellow_cards",
    "was_home",
    "minutes",
    "total_points",
    "opp_team_name",
]

position_stats = {
    "FWD": forward_statistics,
    "GK": goalkeeper_statistics,
    "GKP": goalkeeper_statistics,
    "DEF": defender_statistics,
    "MID": midfielder_statistics,
}

player_stats_19_20_dropped = [
    "first_name",
    "second_name",
    "selected_by_percent",
    "now_cost",
]
player_stats_20_21_dropped = [
    "first_name",
    "second_name",
    "selected_by_percent",
    "now_cost",
    "element_type",
]
players_stats_21_22_dropped = [
    "own_goals",
    "penalties_saved",
    "penalties_missed",
    "saves",
]

mode_features = ["result", "clean_sheets", "minutes"]
mean_features = [
    "bonus",
    "bps",
    "assists",
    "creativity",
    "goals_scored",
    "ict_index",
    "influence",
    "value",
    "threat",
    "result_difference",
    "goals_conceded",
    "total_points",
]
std_features = [
    "assists",
    "creativity",
    "goals_scored",
    "ict_index",
    "influence",
    "threat",
    "goals_conceded",
    "result_difference",
    "value",
    "bps",
    "total_points",
]

gkp_mean_features = [
    "bonus",
    "bps",
    "ict_index",
    "influence",
    "value",
    "penalties_saved",
    "saves",
    "threat",
    "result_difference",
    "goals_conceded",
    "total_points",
]

gkp_std_features = [
    "ict_index",
    "influence",
    "penalties_saved",
    "saves",
    "threat",
    "goals_conceded",
    "result_difference",
    "value",
    "total_points",
]

week1_missing = [
    "assists",
    "bonus",
    "bps",
    "clean_sheets",
    "creativity",
    "element",
    "fixture",
    "goals_conceded",
    "goals_scored",
    "ict_index",
    "influence",
    "minutes",
    "opponent_team",
    "own_goals",
    "penalties_missed",
    "penalties_saved",
    "red_cards",
    "round",
    "saves",
    "selected",
    "team_a_score",
    "team_h_score",
    "threat",
    "total_points",
    "transfers_balance",
    "transfers_in",
    "transfers_out",
    "yellow_cards",
    "result_difference",
    "result",
]
short_term_stats = 3

long_term_stats = 9
